#' Compare glmm between glmmTMB and brms. Repeated measurement per species
#' Simulate
#' 0. linear
#' 1. logistic
#' 2. poisson
#' 3. negative binomial
#' 4. zero inflated negative binomial, constant inflation
#' 5. zero inflated negative binomial, inflation by group

library(tidyverse)
library(easystats)
library(glmmTMB)
library(brms)

# Simulation ----
set.seed(123)
n_species <- 20
measurements_per_species <- 10
n_total <- n_species*measurements_per_species
species <- paste0("species", 1:n_species)
sp_group <- rep(species, each = measurements_per_species)

# Species effect
## on the response
species_effects <- rnorm(n_species, 0, 1)
names(species_effects) <- species
var(species_effects)
## on the zero inflation
species_effects_zi <- runif(n_species, 0, 1)
names(species_effects_zi) <- species

## Predictor
X <- rnorm(n_total, 0, 1) # predictor
eta <- 1 + 0.8 * X + species_effects[sp_group] # Linear predictor

## 0. Linear
Y <- eta + rnorm(n_total, 0, 1) # sigma

## 1. Logistic / Bernoulli. The link function is logistic
Y1 <- rbinom(n_total, 1, plogis(eta))

## 2. Poisson
Y2 <- rpois(n_total, lambda = exp(eta))

## 3. Negative binomial
# Set a high dispersion parameter to reduce randomness generated by NB sampling
k = 10 # dispersion parameter k. var(NB) = mu + mu^2/k
Y3 <- rnbinom(n_total, mu = exp(eta), size = k)

## 4. Zero-inflated negative binomial with constant zi
p_zero <- 0.2 # probability of zero inflation
inflate <- rbinom(n_total, size = 1, prob = p_zero)
counts <- rnbinom(n_total, mu = exp(eta), size = k)
Y4 <- counts*inflate

## 5. Zero-inflated negative binomial with group-specific zi
inflate <- rbinom(n_total, size = 1, prob = species_effects_zi[sp_group])
counts <- rnbinom(n_total, mu = exp(eta), size = k)
Y5 <- counts * inflate

##
tb <- tibble(species = sp_group, X = X, Y = Y, Y1 = Y1, Y2 = Y2, Y3 = Y3, Y4 = Y4, Y5 = Y5)
tb %>%
    pivot_longer(c(-X, -species)) %>%
    ggplot() +
    geom_histogram(aes(x = value, fill = species)) +
    facet_wrap(~name, scales = "free") +
    theme_bw()

# Exampling on negative binomial ----
# Frequentist
mod <- glmmTMB(Y3 ~ X + (1|species), data = tb, family = nbinom2)
summary(mod)

# Residual at the response scale
var(resid(mod, type = "response"))
var(Y3 - predict(mod, type = "response"))

## Pearson residual = (y - y_hat) / sqrt(var(y_hat))
mu_hat <- predict(mod, type = "response")
k <- sigma(mod) # dispersion parameter. not the sigma in lm
var_nb <- mu_hat + mu_hat^2 / k # the residual variance of NB is mu + mu^2/k
var((Y3 - mu_hat) / sqrt(var_nb)) # Pearson residual, (y - mu_hat)  / sqrt(total var)
var(resid(mod, type = "pearson"))

# Random effects
summary(mod)
VarCorr(mod)[[1]][[1]][1] # Model based theoretical estimate of the entire random effect distribution
as_tibble(ranef(mod))[["condval"]] %>% var # Empirical BLUPs (Best Linear Unbiased Predictors) for each group

# Variance at the response scale
## Total variance minus those explained by residuals
#mu_pop <- exp(fixef(mod)$cond[1] + fixef(mod)$cond[2])
fixef_val <- fixef(mod)$cond[1] # Fixed effect (intercept)
rand_intercepts <- ranef(mod)[[1]]$species$`(Intercept)`
mu_species <- exp(fixef_val + rand_intercepts)
var_ran_response <- var(mu_species) # variance of expected counts per species

residuals <- Y3 - predict(mod, type = "response")
var_res <- var(residuals)
var_ran_response / (var_ran_response + var_res)
r2(mod)

# Bayesian ----
mod2 <- brm(Y3 ~ X + (1|species), data = tb, family = negbinomial, chains = 2, cores = 2, iter = 10000, thin = 10, seed = 123)

pp_check(mod2) # Posterior predictive checks
fixef(mod2) # Fixed effect estimates
bayes_R2(mod2)
