#' Simulate
#' 0. linear
#' 1. logistic
#' 2. poisson
#' 3. negative binomial
#' 4. zero-inflated poisson
#' 5. zero-inflated negative binomial

library(tidyverse)
library(easystats)
library(ape)
library(brms)
# library(MASS) # for multivariate gaussian

# Simulate the phylogenetic and species effect ----
# Parameters
set.seed(123)
n_species <- 10
measurements_per_species <- 20
n_total <- n_species*measurements_per_species

# Create phylogeny and covariance matrix
## The diagonals of the cov matrix are the total branch lengths from the root to tips for each species
## The off-diagonals are the total branch lengths from the root to the most recent common ancestor (MRCA) of two species
phylo <- rtree(n = n_species)
phylo <- chronopl(phylo, lambda = 1)
species <- phylo$tip.label
plot(phylo, main = "Mock Phylogeny")
phylo_cov <- vcv(phylo)
diag(phylo_cov)

# Simulate phylogenetic effects.Simulate from a Multivariate Normal Distribution
sd_phylo <- 3 # the sd of brownian motion
phylo_effects <- MASS::mvrnorm(n = 1, mu = rep(0, nrow(phylo_cov)), Sigma = phylo_cov * sd_phylo^2)
names(phylo_effects) <- species
var(phylo_effects)

# Simulate species effect
sp_group <- rep(species, each = measurements_per_species)
species_effects <- rnorm(n_species, 0, 1)
names(species_effects) <- species
var(species_effects)


# Simulate response ----
## Predictor
X <- rnorm(n_total, 0, 1) # predictor

## Linear predictor
eta <- 1 + 0.8 * X + phylo_effects[sp_group] + species_effects[sp_group]

## 0. Linear
Y <- eta + rnorm(n_total, 0, 1) # sigma

## 1. Logistic / Bernoulli. The link function is logistic
Y1 <- rbinom(n_total, 1, plogis(eta))

## 2. Poisson
Y2 <- rpois(n_total, lambda = exp(eta))

## 3. Negative binomial
# Set a high dispersion parameter to reduce randomness generated by NB sampling
Y3 <- rnbinom(n_total, mu = exp(eta), size = 100) # dispersion parameter k. var(NB) = mu + mu^2/k

## 4. Zero-inflated negative binomial

## Table
tb <- tibble(species = sp_group, phylo = sp_group, X = X, Y = Y, Y1 = Y1, Y2 = Y2, Y3 = Y3) %>%
    # species mean
    group_by(phylo) %>%
    mutate(X_bet = mean(X), X_wit = X - X_bet)
hist(Y, breaks = 50)
hist(Y1, breaks = 50)
hist(Y2, breaks = 50)
hist(Y3, breaks = 50)


# 0. Linear  ----
mod <- brm(
    Y ~ X_bet + X_wit + (1|species) + (1|gr(phylo, cov = phylo_cov)),
    data = tb,
    family = gaussian(),
    data2 = list(phylo_cov = phylo_cov),
    chains = 2, cores = 2, iter = 20000, thin = 10, seed = 123,
    control = list(adapt_delta = 0.95)
)

pp_check(mod)
describe_posterior(mod)

## PS. Sp and phylo should have the same contribution to total variance
hyp <- hypothesis(mod, class = NULL, "sd_phylo__Intercept^2 / (sd_phylo__Intercept^2 + sd_species__Intercept^2 + sigma^2) = 0")
plot(hyp)

## Proportion of total variance explained not by residual
bayes_R2(mod)


# 1. Logistic  ----
mod1 <- brm(
    Y1 ~ X_bet + X_wit + (1|species) + (1|gr(phylo, cov = phylo_cov)),
    data = tb,
    family = bernoulli(),
    data2 = list(phylo_cov = phylo_cov),
    chains = 2, cores = 2, iter = 20000, thin = 10, seed = 123,
    control = list(adapt_delta = 0.95)
)

pp_check(mod1)
describe_posterior(mod1)

## PS
hyp <- hypothesis(mod1, class = NULL, "sd_phylo__Intercept^2 / (sd_phylo__Intercept^2 + sd_species__Intercept^2) = 0")
plot(hyp)

## Proportion of total variance explained not by residual
bayes_R2(mod1)

# 2. Poisson ----
mod2 <- brm(
    Y2 ~ X_bet + X_wit + (1|species) + (1|gr(phylo, cov = phylo_cov)),
    data = tb,
    family = poisson,
    data2 = list(phylo_cov = phylo_cov),
    chains = 2, cores = 2, iter = 20000, thin = 10, seed = 123,
    control = list(adapt_delta = 0.95)
)

pp_check(mod2)
describe_posterior(mod2)

## PS
hyp <- hypothesis(mod2, class = NULL, "sd_phylo__Intercept^2 / (sd_phylo__Intercept^2 + sd_species__Intercept^2) = 0")
plot(hyp)

## Proportion of total variance explained not by residual
bayes_R2(mod2)

# 3. Negative binomial ----
mod3 <- brm(
    Y3 ~ X_bet + X_wit + (1|species) + (1|gr(phylo, cov = phylo_cov)),
    data = tb,
    family = "negbinomial2",
    data2 = list(phylo_cov = phylo_cov),
    chains = 2, cores = 2, iter = 20000, thin = 10, seed = 123,
    control = list(adapt_delta = 0.95)
)

pp_check(mod3)
describe_posterior(mod3)

## PS
# phylogenetic signal
# In NB, there is a sigma estimate to describe variability beyond poisson (which equals mean)
hyp <- hypothesis(mod3, class = NULL, "sd_phylo__Intercept^2 / (sd_phylo__Intercept^2 + sd_species__Intercept^2 + sigma^2) = 0")
plot(hyp)

## Proportion of total variance explained not by residual
bayes_R2(mod3)


# Compare the models ----
bayes_R2(mod)
bayes_R2(mod1)
bayes_R2(mod2)
bayes_R2(mod3)
